WITH ECOLI_RANK AS (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 AS P_RANK
    FROM ECOLI_DATA
)

SELECT ID, 
    CASE
        WHEN P_RANK <= 25 THEN 'CRITICAL'
        WHEN P_RANK <= 50 THEN 'HIGH'
        WHEN P_RANK <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_RANK
ORDER BY ID























# WITH ECOLI_RANK AS (
#     SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100 AS P_RANK
#     FROM ECOLI_DATA
# )
# SELECT ID, 
#     CASE
#         WHEN P_RANK <= 25 THEN 'CRITICAL'
#         WHEN P_RANK <= 50 THEN 'HIGH'
#         WHEN P_RANK <= 75 THEN 'MEDIUM'
#         ELSE 'LOW'
#     END AS COLONY_NAME
# FROM ECOLI_RANK
# ORDER BY ID