
WITH A AS (
    SELECT HISTORY_ID, B.CAR_TYPE, B.DAILY_FEE,
        DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS DURATION,
        CASE
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 'NONE'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
        JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
)

SELECT A.HISTORY_ID,
    FLOOR((A.DAILY_FEE * A.DURATION * (100-COALESCE(B.DISCOUNT_RATE,0))) / 100) AS FEE
FROM A
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC