SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES






















# SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
# FROM USED_GOODS_USER A
# JOIN (
#     SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
#     FROM USED_GOODS_BOARD
#     WHERE STATUS = 'DONE'
#     GROUP BY WRITER_ID
#     HAVING TOTAL_SALES >= 700000
# ) B ON A.USER_ID = B.WRITER_ID
# ORDER BY B.TOTAL_SALES