SELECT A.ID, A.GENOTYPE, B.PARENT_GENOTYPE
FROM ECOLI_DATA A
JOIN (
    SELECT ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
) B ON A.PARENT_ID = B.ID
WHERE (A.GENOTYPE & PARENT_GENOTYPE) = PARENT_GENOTYPE
ORDER BY A.ID