SELECT SUM(SCORE) AS SCORE, A.EMP_NO, B.EMP_NAME, POSITION, EMAIL
FROM HR_GRADE A JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO, YEAR
ORDER BY SUM(SCORE) DESC
LIMIT 1











# SELECT SUM(SCORE) AS SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
# FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
# GROUP BY EMP_NO, YEAR
# HAVING YEAR = '2022'
# ORDER BY SCORE DESC
# LIMIT 1